Table processsubscriptionsactivity9999 {
}

Table processsubscriptionsactivity_types9999 {
}

Table subscriptionreportactivity {
}

Table subscriptionreportactivity_sample {
}

Table submission_stage_data {
}

Table samplereportapprovalnotificationactivity_sample {
}

Table samplereportapprovalactivity {
}

Table samplereportfaxactivity {
}

Table pendingdigest {
}

Table samplereportapprovalnotificationactivity {
}

Table irsamplesubmissionactivity {
}

Table abstractsamplesubmissionactivity {
}

Table reportfillactivity {
}

Table processsubscriptionsactivity_types {
}

Table activity {
}

Table samplereportfax_labids {
}

Table samplesubmissionactivity {
}

Table processsubscriptionsactivity {
}

