Table "assetmgmt.asset" {
 	"id" bigint  [primary key] 
 	"version" integer   
 	"accountnumber" varchar(14)  
 	"name" varchar(30)  
 	"applicationid" bigint   
 	"manufacturerid" bigint   
 } 
 
 Table "assetmgmt.component" {
 	"id" bigint  [primary key] 
 	"version" integer   
 	"name" varchar(30)  
 	"alternatename" varchar(30)  
 	"active" boolean  [default: false] 
 	"hydraulicsystempressure" integer   
 	"sumpcapacity" integer   
 	"sumpcapacityunit" varchar(10)  
 	"defaulttimeunit" varchar(15)  
 	"sampleinterval" integer   
 	"sampleintervalunit" varchar(15)  
 	"wildcard1" varchar(30)  
 	"wildcard2" varchar(30)  
 	"wildcard3" varchar(30)  
 	"assetid" bigint   
 	"applicationid" bigint   
 	"componentmodelid" bigint   
 	"typeid" bigint   
 	"filtertypeid" bigint   
 	"micronrating" integer   
 	"fluidmanufacturerid" bigint   
 	"fluidid" bigint   
 	"gradeid" bigint   
 	"manufacturerid" bigint   
 } 
 
 Table "assetmgmt.jarlabel" {
 	"id" bigint  [primary key] 
 	"version" integer   
 	"active" boolean  [default: false] 
 	"barcode" varchar(11)  
 	"ordernumber" varchar(6)  
 	"itemnumber" varchar(12)  
 	"type" varchar(12)  
 	"price" varchar(255)  
 	"currencycode" varchar(255)  
 	"datereceived" timestamp   
 	"testpackage" varchar(6)  
 	"countryrestriction" varchar(3)  
 	"internal" boolean  [default: false] 
 	"accountnumber" varchar(14)  
 	"shippedfrom" varchar(5)  
 	"rushcharge" varchar(9)  
 	"rushrequestedby" varchar(255)  
 	"rushticket" varchar(255)  
 } 
 
 Table "assetmgmt.rowcount" {
 	"tablename" varchar(255) [primary key] 
 	"totalrows" bigint   
 } 
 
 Table "assetmgmt.sample" {
 	"id" bigint  [primary key] 
 	"version" integer   
 	"labnumber" varchar(14)  
 	"partnersampleid" varchar(16)  
 	"status" varchar(20)  
 	"dataanalyst" varchar(5)  
 	"severity" integer   
 	"datesampled" timestamp   
 	"datesampledincomplete" varchar(8)  
 	"datesubmitted" timestamp   
 	"datereceived" timestamp   
 	"datecompleted" timestamp   
 	"dateprocessed" timestamp   
 	"billed" boolean  [default: false] 
 	"dateapproved" timestamp   
 	"datereevaluated" timestamp   
 	"feedbackstatus" varchar(12)  
 	"datefeedbackclosed" timestamp   
 	"approvalcomments" varchar(1536)  
 	"componenttime" integer   
 	"componenttimeunit" varchar(15)  
 	"fluidtime" integer   
 	"fluidtimeunit" varchar(15)  
 	"fluidadded" integer   
 	"fluidaddedunit" varchar(10)  
 	"fluidchange" varchar(8)  
 	"filterchange" varchar(8)  
 	"misc" varchar(100)  
 	"wildcard1" varchar(30)  
 	"wildcard2" varchar(30)  
 	"wildcard3" varchar(30)  
 	"testpackage" varchar(255)  
 	"purchaseorder" varchar(255)  
 	"rushcharge" varchar(9)  
 	"rushrequestedby" varchar(255)  
 	"rushticket" varchar(255)  
 	"notestoanalyst" varchar(120)  
 	"componentid" bigint   
 	"jarlabelid" bigint   
 	"fluidtype" varchar(11)  
 	"filtertypeid" bigint   
 	"micronrating" integer   
 	"fluidid" bigint   
 	"gradeid" bigint   
 	"location" varchar(3)  
 	"rushbilled" boolean  [default: false] 
 	"testprice" varchar(255)  
 	"testpricecurrencycode" varchar(255)  
 } 
 
 
Ref: "assetmgmt.asset".manufacturerid > "reference.manufacturer".id
Ref: "assetmgmt.asset".applicationid > "reference.application".id
Ref: "assetmgmt.component".manufacturerid > "reference.manufacturer".id
Ref: "assetmgmt.component".gradeid > "reference.fluidgrade".id
Ref: "assetmgmt.component".applicationid > "reference.application".id
Ref: "assetmgmt.component".assetid > "assetmgmt.asset".id
Ref: "assetmgmt.component".fluidid > "reference.fluid".id
Ref: "assetmgmt.component".typeid > "reference.componenttype".id
Ref: "assetmgmt.component".fluidmanufacturerid > "reference.manufacturer".id
Ref: "assetmgmt.component".componentmodelid > "reference.componentmodel".id
Ref: "assetmgmt.component".filtertypeid > "reference.filtertype".id
Ref: "assetmgmt.sample".componentid > "assetmgmt.component".id
Ref: "assetmgmt.sample".gradeid > "reference.fluidgrade".id
Ref: "assetmgmt.sample".filtertypeid > "reference.filtertype".id
Ref: "assetmgmt.sample".fluidid > "reference.fluid".id
Ref: "assetmgmt.sample".jarlabelid > "assetmgmt.jarlabel".id 
 
Table "audit_assetmgmt.asset_aud" {
 	"aud_tstamp" timestamp   
 	"aud_userid" text   
 	"aud_operation" character(1)  
 	"id" bigint   
 	"version" integer   
 	"accountnumber" varchar(14)  
 	"name" varchar(30)  
 	"applicationid" bigint   
 	"manufacturerid" bigint   
 } 
 
 Table "audit_assetmgmt.component_aud" {
 	"aud_tstamp" timestamp   
 	"aud_userid" text   
 	"aud_operation" character(1)  
 	"id" bigint   
 	"version" integer   
 	"name" varchar(30)  
 	"alternatename" varchar(30)  
 	"active" boolean   
 	"hydraulicsystempressure" integer   
 	"sumpcapacity" integer   
 	"sumpcapacityunit" varchar(10)  
 	"defaulttimeunit" varchar(15)  
 	"sampleinterval" integer   
 	"sampleintervalunit" varchar(15)  
 	"wildcard1" varchar(30)  
 	"wildcard2" varchar(30)  
 	"wildcard3" varchar(30)  
 	"assetid" bigint   
 	"applicationid" bigint   
 	"componentmodelid" bigint   
 	"typeid" bigint   
 	"filtertypeid" bigint   
 	"micronrating" integer   
 	"fluidmanufacturerid" bigint   
 	"fluidid" bigint   
 	"gradeid" bigint   
 	"manufacturerid" bigint   
 } 
 
 Table "audit_assetmgmt.jarlabel_aud" {
 	"aud_tstamp" timestamp   
 	"aud_userid" text   
 	"aud_operation" character(1)  
 	"id" bigint   
 	"version" integer   
 	"active" boolean   
 	"barcode" varchar(11)  
 	"ordernumber" varchar(6)  
 	"itemnumber" varchar(12)  
 	"type" varchar(12)  
 	"price" varchar(255)  
 	"currencycode" varchar(255)  
 	"datereceived" timestamp   
 	"testpackage" varchar(6)  
 	"countryrestriction" varchar(3)  
 	"internal" boolean   
 	"accountnumber" varchar(14)  
 	"shippedfrom" varchar(5)  
 	"rushcharge" varchar(9)  
 	"rushrequestedby" varchar(255)  
 	"rushticket" varchar(255)  
 } 
 
 Table "audit_assetmgmt.sample_aud" {
 	"aud_tstamp" timestamp   
 	"aud_userid" text   
 	"aud_operation" character(1)  
 	"id" bigint   
 	"version" integer   
 	"labnumber" varchar(14)  
 	"partnersampleid" varchar(16)  
 	"status" varchar(20)  
 	"dataanalyst" varchar(5)  
 	"severity" integer   
 	"datesampled" timestamp   
 	"datesampledincomplete" varchar(8)  
 	"datesubmitted" timestamp   
 	"datereceived" timestamp   
 	"datecompleted" timestamp   
 	"dateprocessed" timestamp   
 	"billed" boolean   
 	"dateapproved" timestamp   
 	"datereevaluated" timestamp   
 	"feedbackstatus" varchar(12)  
 	"datefeedbackclosed" timestamp   
 	"approvalcomments" varchar(1536)  
 	"componenttime" integer   
 	"componenttimeunit" varchar(15)  
 	"fluidtime" integer   
 	"fluidtimeunit" varchar(15)  
 	"fluidadded" integer   
 	"fluidaddedunit" varchar(10)  
 	"fluidchange" varchar(8)  
 	"filterchange" varchar(8)  
 	"misc" varchar(100)  
 	"wildcard1" varchar(30)  
 	"wildcard2" varchar(30)  
 	"wildcard3" varchar(30)  
 	"testpackage" varchar(255)  
 	"purchaseorder" varchar(255)  
 	"rushcharge" varchar(9)  
 	"rushrequestedby" varchar(255)  
 	"rushticket" varchar(255)  
 	"notestoanalyst" varchar(120)  
 	"componentid" bigint   
 	"jarlabelid" bigint   
 	"fluidtype" varchar(11)  
 	"filtertypeid" bigint   
 	"micronrating" integer   
 	"fluidid" bigint   
 	"gradeid" bigint   
 	"location" varchar(3)  
 	"rushbilled" boolean   
 	"testprice" varchar(255)  
 	"testpricecurrencycode" varchar(255)  
 } 
 
  
 
Table "audit_reference.application_aud" {
 	"aud_tstamp" timestamp   
 	"aud_userid" text   
 	"aud_operation" character(1)  
 	"id" bigint   
 	"version" integer   
 	"code" varchar(5)  
 	"name" varchar(35)  
 	"parentapplicationid" bigint   
 } 
 
 Table "audit_reference.componentmodel_aud" {
 	"aud_tstamp" timestamp   
 	"aud_userid" text   
 	"aud_operation" character(1)  
 	"id" bigint   
 	"version" integer   
 	"code" varchar(3)  
 	"name" varchar(30)  
 	"manufacturerid" bigint   
 } 
 
 Table "audit_reference.componenttype_aud" {
 	"aud_tstamp" timestamp   
 	"aud_userid" text   
 	"aud_operation" character(1)  
 	"id" bigint   
 	"version" integer   
 	"code" varchar(5)  
 	"name" varchar(30)  
 	"fluidtype" varchar(11)  
 	"parenttypeid" bigint   
 } 
 
 Table "audit_reference.filtertype_aud" {
 	"aud_tstamp" timestamp   
 	"aud_userid" text   
 	"aud_operation" character(1)  
 	"id" bigint   
 	"version" integer   
 	"code" varchar(2)  
 	"name" varchar(35)  
 } 
 
 Table "audit_reference.fluid_aud" {
 	"aud_tstamp" timestamp   
 	"aud_userid" text   
 	"aud_operation" character(1)  
 	"id" bigint   
 	"version" integer   
 	"code" varchar(3)  
 	"name" varchar(50)  
 	"type" varchar(11)  
 	"manufacturerid" bigint   
 	"fluidgradeid" bigint   
 } 
 
 Table "audit_reference.fluidgrade_aud" {
 	"aud_tstamp" timestamp   
 	"aud_userid" text   
 	"aud_operation" character(1)  
 	"id" bigint   
 	"version" integer   
 	"code" varchar(3)  
 	"name" varchar(30)  
 	"parentgradeid" bigint   
 } 
 
 Table "audit_reference.manufacturer_aud" {
 	"aud_tstamp" timestamp   
 	"aud_userid" text   
 	"aud_operation" character(1)  
 	"id" bigint   
 	"version" integer   
 	"code" varchar(5)  
 	"name" varchar(35)  
 	"producttype" varchar(255)  
 } 
 
  
 
Table "labreference.base_test_price" {
 	"id" bigint  [default: `nextval('labreference.base_test_price_id_seq'::regclass)`, primary key] 
 	"location_id" bigint   
 	"currency_id" bigint   
 	"test_id" bigint   
 	"cost" numeric   
 	"base_price" numeric   
 } 
 
 Table "labreference.currency" {
 	"id" bigint  [default: `nextval('labreference.currency_id_seq'::regclass)`, primary key] 
 	"code" varchar(3)  
 	"symbol" varchar(2)  
 } 
 
 Table "labreference.currency_at_location" {
 	"location_id" bigint   
 	"currency_id" bigint   
 	"default_gpm" numeric   
 	"default_rush_fee" numeric   
 	"default_reporting_fee_usd" numeric   
 } 
 
 Table "labreference.laboratory" {
 	"id" bigint  [default: `nextval('labreference.laboratory_id_seq'::regclass)`, primary key] 
 	"name" varchar   
 	"code" varchar(1)  
 	"base_pricing_laboratory" varchar(1)  
 	"location_id" bigint   
 } 
 
 Table "labreference.location" {
 	"id" bigint  [default: `nextval('labreference.location_id_seq'::regclass)`, primary key] 
 	"name" varchar   
 	"reporting_name" varchar   
 	"type" varchar   
 	"contact" varchar   
 	"address1" varchar   
 	"address2" varchar   
 	"city" varchar   
 	"region" varchar   
 	"post_code" varchar   
 	"country_code" varchar   
 	"country_name" varchar   
 	"phone_number" varchar   
 	"lims_source_code" varchar   
 } 
 
 Table "labreference.test" {
 	"id" bigint  [default: `nextval('labreference.test_id_seq'::regclass)`, primary key] 
 	"method" varchar   
 	"code" varchar(5)  
 	"name" varchar   
 	"report_name" varchar   
 	"required_volume" varchar   
 	"note" varchar   
 	"analyte" varchar   
 	"active" boolean   
 	"for_sale" boolean   
 	"unit_of_measure" varchar   
 	"inserted_user" varchar   
 	"inserted_timestamp" timestamp   
 	"updated_user" varchar   
 	"updated_timestamp" timestamp   
 } 
 
 Table "labreference.test_by_fluid_type" {
 	"test_id" bigint   
 	"fluid_type" varchar(1)  
 } 
 
 Table "labreference.test_package" {
 	"id" bigint  [default: `nextval('labreference.test_package_id_seq'::regclass)`, primary key] 
 	"name" varchar   
 	"inserted_user" varchar   
 	"inserted_timestamp" timestamp   
 	"updated_user" varchar   
 	"updated_timestamp" timestamp   
 } 
 
 Table "labreference.test_package_content" {
 	"test_package_id" bigint   
 	"test_id" bigint   
 	"id" bigint  [default: `nextval('labreference.test_package_content_id_seq'::regclass)`, primary key] 
 	"inserted_user" varchar   
 	"inserted_timestamp" timestamp   
 	"updated_user" varchar   
 	"updated_timestamp" timestamp   
 } 
 
 Table "labreference.test_rule_by_location" {
 	"test_id" bigint   
 	"location_id" bigint   
 	"outsourced_value" varchar   
 	"rush_value" varchar(1)  
 	"outsource_lab_location_id" bigint   
 } 
 
 
Ref: "labreference.base_test_price".currency_id > "labreference.currency".id
Ref: "labreference.base_test_price".test_id > "labreference.test".id
Ref: "labreference.base_test_price".location_id > "labreference.location".id
Ref: "labreference.currency_at_location".currency_id > "labreference.currency".id
Ref: "labreference.currency_at_location".location_id > "labreference.location".id
Ref: "labreference.laboratory".location_id > "labreference.location".id
Ref: "labreference.test_package_content".test_package_id > "labreference.test_package".id
Ref: "labreference.test_package_content".test_id > "labreference.test".id
Ref: "labreference.test_rule_by_location".test_id > "labreference.test".id
Ref: "labreference.test_rule_by_location".outsource_lab_location_id > "labreference.location".id
Ref: "labreference.test_rule_by_location".location_id > "labreference.location".id 
 
Table "pricelist.price_list" {
 	"id" bigint  [default: `nextval('pricelist.price_list_id_seq'::regclass)`, primary key] 
 	"plp_id" bigint   
 	"program_id" bigint   
 	"laboratory_id" bigint   
 	"currency_id" bigint   
 	"gpm" numeric   
 	"rush_fee" numeric   
 	"reporting_fee" numeric   
 } 
 
 Table "pricelist.price_list_override" {
 	"price_list_id" bigint   
 	"test_id" bigint   
 	"price" numeric   
 } 
 
 Table "pricelist.test_package_override" {
 	"price_list_id" bigint   
 	"test_package_id" bigint   
 	"price" numeric   
 } 
 
 
Ref: "pricelist.price_list_override".price_list_id > "pricelist.price_list".id
Ref: "pricelist.test_package_override".price_list_id > "pricelist.price_list".id 
 
 
 
Table "reference.application" {
 	"id" bigint  [primary key] 
 	"version" integer   
 	"code" varchar(5)  
 	"name" varchar(35)  
 	"parentapplicationid" bigint   
 } 
 
 Table "reference.componentmodel" {
 	"id" bigint  [primary key] 
 	"version" integer   
 	"code" varchar(3)  
 	"name" varchar(30)  
 	"manufacturerid" bigint   
 } 
 
 Table "reference.componenttype" {
 	"id" bigint  [primary key] 
 	"version" integer   
 	"code" varchar(5)  
 	"name" varchar(30)  
 	"fluidtype" varchar(11)  
 	"parenttypeid" bigint   
 } 
 
 Table "reference.filtertype" {
 	"id" bigint  [primary key] 
 	"version" integer   
 	"code" varchar(2)  
 	"name" varchar(35)  
 } 
 
 Table "reference.fluid" {
 	"id" bigint  [primary key] 
 	"version" integer   
 	"code" varchar(3)  
 	"name" varchar(50)  
 	"type" varchar(11)  
 	"manufacturerid" bigint   
 	"fluidgradeid" bigint   
 } 
 
 Table "reference.fluidgrade" {
 	"id" bigint  [primary key] 
 	"version" integer   
 	"code" varchar(3)  
 	"name" varchar(30)  
 	"parentgradeid" bigint   
 } 
 
 Table "reference.manufacturer" {
 	"id" bigint  [primary key] 
 	"version" integer   
 	"code" varchar(5)  
 	"name" varchar(35)  
 	"producttype" varchar(255)  
 } 
 
 
Ref: "reference.application".parentapplicationid > "reference.application".id
Ref: "reference.componentmodel".manufacturerid > "reference.manufacturer".id
Ref: "reference.componenttype".parenttypeid > "reference.componenttype".id
Ref: "reference.fluid".fluidgradeid > "reference.fluidgrade".id
Ref: "reference.fluid".manufacturerid > "reference.manufacturer".id
Ref: "reference.fluidgrade".parentgradeid > "reference.fluidgrade".id 
 
Table "wip.account_pricing" {
 	"account_id" integer  [default: `nextval('wip.account_pricing_account_id_seq'::regclass)`, primary key] 
 	"location_id" integer   
 	"currency_id" integer   
 	"test_id" integer   
 	"override_price" numeric   
 	"inserted_user" varchar   
 	"inserted_timestamp" timestamp   
 	"updated_user" varchar   
 	"updated_timestamp" timestamp   
 } 
 
 Table "wip.additional_test" {
 	"barcode_id" integer  [primary key] 
 	"test_id_id" integer   
 	"billed" boolean   
 	"inserted_user" varchar   
 	"inserted_timestamp" timestamp   
 	"updated_user" varchar   
 	"updated_timestamp" timestamp   
 } 
 
 Table "wip.analyte" {
 	"analyte_id" integer  [default: `nextval('wip.analyte_analyte_id_seq'::regclass)`, primary key] 
 	"name" varchar   
 	"unit_of_measure" varchar   
 	"code" varchar   
 	"report_name" varchar   
 	"reportable" boolean   
 	"inserted_user" varchar   
 	"inserted_timestamp" timestamp   
 	"updated_user" varchar   
 	"updated_timestamp" timestamp   
 } 
 
 Table "wip.comment_code" {
 	"comment_code_id" integer  [primary key] 
 	"code" varchar   
 	"severity" integer   
 	"mnemonic" varchar   
 	"type" varchar   
 	"version" varchar   
 	"status" varchar   
 	"comment" varchar   
 	"inserted_user" varchar   
 	"inserted_timestamp" timestamp   
 	"updated_user" varchar   
 	"updated_timestamp" timestamp   
 } 
 
 Table "wip.component_type_restriction" {
 	"test_id" integer  [primary key] 
 	"component_type_mask" varchar  [primary key] 
 	"restriction_type" varchar   
 	"inserted_user" varchar   
 	"inserted_timestamp" timestamp   
 	"updated_user" varchar   
 	"updated_timestamp" timestamp   
 } 
 
 Table "wip.distribution_point" {
 	"distribution_point_id" integer  [primary key] 
 	"distribution_point_name" varchar   
 	"distribution_point_code" varchar   
 	"location_id" integer   
 	"created_at" varchar   
 	"updated_at" varchar   
 	"last_edited" varchar   
 	"easy_post_id" varchar   
 	"invoice_ref_counter" integer   
 	"easy_post_carrier_id" varchar   
 	"inventory_ref_counter" integer   
 	"timezone" varchar   
 	"inserted_user" varchar   
 	"inserted_timestamp" timestamp   
 	"updated_user" varchar   
 	"updated_timestamp" timestamp   
 } 
 
 Table "wip.methods" {
 	"method_id" integer  [primary key] 
 	"name" varchar   
 	"description" varchar   
 	"image" varchar   
 	"inserted_user" varchar   
 	"inserted_timestamp" timestamp   
 	"updated_user" varchar   
 	"updated_timestamp" timestamp   
 } 
 
 Table "wip.plp_gpm" {
 	"plp_id" integer  [primary key] 
 	"GPM" varchar   
 	"inserted_user" varchar   
 	"inserted_timestamp" timestamp   
 	"updated_user" varchar   
 	"updated_timestamp" timestamp   
 } 
 
 Table "wip.plp_pricing" {
 	"plp_id" integer  [primary key] 
 	"location_id" integer   
 	"currency_id" integer   
 	"test_id" integer   
 	"override_price" numeric   
 	"inserted_user" varchar   
 	"inserted_timestamp" timestamp   
 	"updated_user" varchar   
 	"updated_timestamp" timestamp   
 } 
 
 Table "wip.procedures" {
 	"procedure_id" integer  [primary key] 
 	"analyte_id" integer   
 	"name" integer   
 	"order" integer   
 	"inserted_user" varchar   
 	"inserted_timestamp" timestamp   
 	"updated_user" varchar   
 	"updated_timestamp" timestamp   
 } 
 
 Table "wip.program_gpm" {
 	"program_id" integer  [primary key] 
 	"GPM" varchar   
 	"inserted_user" varchar   
 	"inserted_timestamp" timestamp   
 	"updated_user" varchar   
 	"updated_timestamp" timestamp   
 } 
 
 Table "wip.program_pricing" {
 	"program_id" integer  [primary key] 
 	"location_id" integer   
 	"currency_id" integer   
 	"test_id" integer   
 	"override_price" numeric   
 	"inserted_user" varchar   
 	"inserted_timestamp" timestamp   
 	"updated_user" varchar   
 	"updated_timestamp" timestamp   
 } 
 
 Table "wip.result" {
 	"result_id" integer  [primary key] 
 	"sample_id" integer   
 	"procedure_id" integer   
 	"analyte_id" integer   
 	"value" varchar   
 	"is_number" boolean   
 	"severity_flag" varchar   
 	"replicate" integer   
 	"final_result" boolean   
 	"inserted_user" varchar   
 	"inserted_timestamp" timestamp   
 	"updated_user" varchar   
 	"updated_timestamp" timestamp   
 } 
 
 Table "wip.sample_comment" {
 	"sample_comment_id" integer  [default: `nextval('wip.sample_comment_sample_comment_id_seq'::regclass)`, primary key] 
 	"sample_id" integer   
 	"position" integer   
 	"comment_code_id" integer   
 	"customer_work_order" varchar   
 	"customer_finding" varchar   
 	"customer_comment" varchar   
 	"estimated_saving" numeric   
 	"last_modification" timestamp   
 	"inserted_user" varchar   
 	"inserted_timestamp" timestamp   
 	"updated_user" varchar   
 	"updated_timestamp" timestamp   
 } 
 
 Table "wip.test_analyte" {
 	"analyte_id" integer  [primary key] 
 	"test_id" integer   
 	"legacy_analyte_code" varchar   
 	"name" varchar   
 	"active" boolean   
 	"inserted_user" varchar   
 	"inserted_timestamp" timestamp   
 	"updated_user" varchar   
 	"updated_timestamp" timestamp   
 } 
 
 Table "wip.test_package_grade_option" {
 	"test_package_id" integer   
 	"test_package_profile_id" integer   
 	"lube_grade_id" integer   
 	"inserted_user" varchar   
 	"inserted_timestamp" timestamp   
 	"updated_user" varchar   
 	"updated_timestamp" timestamp   
 } 
 
 Table "wip.test_package_profile" {
 	"test_package_profile_id" integer  [primary key] 
 	"kit_id" integer   
 	"component_type_id" integer   
 	"inserted_user" varchar   
 	"inserted_timestamp" timestamp   
 	"updated_user" varchar   
 	"updated_timestamp" timestamp   
 } 
 
 Table "wip.test_prerequisite" {
 	"test_id" integer   
 	"prerequisite_test_id" integer  [primary key] 
 	"inserted_user" varchar   
 	"inserted_timestamp" timestamp   
 	"updated_user" varchar   
 	"updated_timestamp" timestamp   
 } 
 
 
Ref: "wip.sample_comment".comment_code_id > "wip.comment_code".comment_code_id
Ref: "wip.test_analyte".analyte_id > "wip.analyte".analyte_id
Ref: "wip.test_package_grade_option".test_package_profile_id > "wip.test_package_profile".test_package_profile_id 
 
