Table "asset" {
 	"id" bigint  [primary key] 
 	"version" integer   
 	"accountnumber" varchar(14)  
 	"name" varchar(30)  
 	"applicationid" bigint   
 	"manufacturerid" bigint   
 } 
 
 Table "component" {
 	"id" bigint  [primary key] 
 	"version" integer   
 	"name" varchar(30)  
 	"alternatename" varchar(30)  
 	"active" boolean  [default: false] 
 	"hydraulicsystempressure" integer   
 	"sumpcapacity" integer   
 	"sumpcapacityunit" varchar(10)  
 	"defaulttimeunit" varchar(15)  
 	"sampleinterval" integer   
 	"sampleintervalunit" varchar(15)  
 	"wildcard1" varchar(30)  
 	"wildcard2" varchar(30)  
 	"wildcard3" varchar(30)  
 	"assetid" bigint   
 	"applicationid" bigint   
 	"componentmodelid" bigint   
 	"typeid" bigint   
 	"filtertypeid" bigint   
 	"micronrating" integer   
 	"fluidmanufacturerid" bigint   
 	"fluidid" bigint   
 	"gradeid" bigint   
 	"manufacturerid" bigint   
 } 
 
 Table "databasechangelog" {
 	"id" varchar(255)  
 	"author" varchar(255)  
 	"filename" varchar(255)  
 	"dateexecuted" timestamp   
 	"orderexecuted" integer   
 	"exectype" varchar(10)  
 	"md5sum" varchar(35)  
 	"description" varchar(255)  
 	"comments" varchar(255)  
 	"tag" varchar(255)  
 	"liquibase" varchar(20)  
 	"contexts" varchar(255)  
 	"labels" varchar(255)  
 	"deployment_id" varchar(10)  
 } 
 
 Table "databasechangeloglock" {
 	"id" integer  [primary key] 
 	"locked" boolean   
 	"lockgranted" timestamp   
 	"lockedby" varchar(255)  
 } 
 
 Table "jarlabel" {
 	"id" bigint  [primary key] 
 	"version" integer   
 	"active" boolean  [default: false] 
 	"barcode" varchar(11)  
 	"ordernumber" varchar(6)  
 	"itemnumber" varchar(12)  
 	"type" varchar(12)  
 	"price" varchar(255)  
 	"currencycode" varchar(255)  
 	"datereceived" timestamp   
 	"testpackage" varchar(6)  
 	"countryrestriction" varchar(3)  
 	"internal" boolean  [default: false] 
 	"accountnumber" varchar(14)  
 	"shippedfrom" varchar(5)  
 	"rushcharge" varchar(9)  
 	"rushrequestedby" varchar(255)  
 	"rushticket" varchar(255)  
 } 
 
 Table "rowcount" {
 	"tablename" varchar(255) [primary key] 
 	"totalrows" bigint   
 } 
 
 Table "sample" {
 	"id" bigint  [primary key] 
 	"version" integer   
 	"labnumber" varchar(14)  
 	"partnersampleid" varchar(16)  
 	"status" varchar(20)  
 	"dataanalyst" varchar(5)  
 	"severity" integer   
 	"datesampled" timestamp   
 	"datesampledincomplete" varchar(8)  
 	"datesubmitted" timestamp   
 	"datereceived" timestamp   
 	"datecompleted" timestamp   
 	"dateprocessed" timestamp   
 	"billed" boolean  [default: false] 
 	"dateapproved" timestamp   
 	"datereevaluated" timestamp   
 	"feedbackstatus" varchar(12)  
 	"datefeedbackclosed" timestamp   
 	"approvalcomments" varchar(1536)  
 	"componenttime" integer   
 	"componenttimeunit" varchar(15)  
 	"fluidtime" integer   
 	"fluidtimeunit" varchar(15)  
 	"fluidadded" integer   
 	"fluidaddedunit" varchar(10)  
 	"fluidchange" varchar(8)  
 	"filterchange" varchar(8)  
 	"misc" varchar(100)  
 	"wildcard1" varchar(30)  
 	"wildcard2" varchar(30)  
 	"wildcard3" varchar(30)  
 	"testpackage" varchar(255)  
 	"purchaseorder" varchar(255)  
 	"rushcharge" varchar(9)  
 	"rushrequestedby" varchar(255)  
 	"rushticket" varchar(255)  
 	"notestoanalyst" varchar(120)  
 	"componentid" bigint   
 	"jarlabelid" bigint   
 	"fluidtype" varchar(11)  
 	"filtertypeid" bigint   
 	"micronrating" integer   
 	"fluidid" bigint   
 	"gradeid" bigint   
 	"location" varchar(3)  
 	"rushbilled" boolean  [default: false] 
 	"testprice" varchar(255)  
 	"testpricecurrencycode" varchar(255)  
 } 
 
 
Ref: "component".assetid > "asset".id
Ref: "sample".componentid > "component".id
Ref: "sample".jarlabelid > "jarlabel".id 
 
