Table persistentreportcontext {
	id bigint 
	version integer 
	report varchar(50) 
	created timestamp without time zone 
	saved boolean 
	name varchar(64) 
	owner bigint 
	sendtoowner boolean 
	nextexecution timestamp without time zone 
	executeat time without time zone 
	militarytime boolean 
	timezone varchar(42) 
	repeattype varchar(7) 
	repeatstart date 
	repeatend date 
	yearlydenomination varchar(6) 
	yearlydayofweek varchar(11) 
	yearlyrepeatmonths varchar(85) 
	monthlyinterval integer 
	monthlydenomination varchar(6) 
	monthlydayofweek varchar(11) 
	monthlyrepeatdays varchar(85) 
	weeklyinterval integer 
	weeklyrepeatdays varchar(85) 
	dailyinterval integer 
	timeframe varchar(84) 
	relativeperiod integer 
	firstmonthinyear integer 
	firstdayinweek integer 
	forceweekday boolean 
	timeframestart date 
	timeframeend date 
	attachreport boolean [default:'false']
}

Table attachment {
	id bigint [default:'nextval('polaris.attachment_id_seq'::regclass)']
	version integer 
	type varchar(32) 
	sample bigint 
	name varchar(128) 
	uploaddate timestamp without time zone 
	location varchar(256) 
}

Table powerbi_application_averages {
	appl_limskey varchar(5) 
	stat_year integer 
	application_name varchar(35) 
	taking_action_feedback double precision 
	high_severity_pct double precision 
	components_sampled_pct double precision 
	shipping_time_days double precision 
	online_sample_submission_pct double precision 
}

Table clientversion {
	brand varchar(30) 
	minimumsemanticversion varchar(12) 
	enabled boolean 
}

Table fluid {
	id bigint 
	limskey varchar(3) 
	name varchar(50) 
	type character(1) 
	restrictedstandard bigint 
	manufacturerid bigint 
	version integer 
}

Table authorityoverride {
	accountmask varchar(14) 
	feature varchar(255) 
	permission integer 
	person_id bigint 
}

Table billingconfiguration {
	account bigint 
	address bigint 
	phone bigint 
	emailaddress varchar(128) 
	fax bigint 
	invoicelevel varchar(1) 
	invoicedaysdue integer 
	invoicefrequency varchar(9) 
	ponumber varchar(20) 
	splitpercentage numeric 
	nitnumber varchar(20) 
	id bigint 
	language varchar(2) 
	name varchar(50) 
	order_po_number varchar(20) 
	next_price_review varchar(8) 
	ticket_no varchar(13) 
}

Table commentcode {
	id bigint 
	version integer 
	mnemonic varchar(24) 
	limskey varchar(5) 
	severity integer 
	type varchar(255) 
}

Table userregistration {
	id bigint 
	address bigint 
	barcode bigint 
	submitteddistributor varchar(128) 
	submittedcompanyname varchar(128) 
}

Table maintenancerecord {
	id bigint 
	component bigint 
	maintenancedate timestamp without time zone 
	componenttime bigint 
	componenttimeuom varchar(2) 
	fluidchange varchar(1) 
	filterchange varchar(1) 
	action varchar(16) 
	performedby varchar(64) 
	workorder varchar(16) 
	comments varchar(128) 
}

Table filtertype {
	id bigint 
	version integer 
	limskey varchar(2) 
	name varchar(35) 
}

Table testkittype {
	unittype varchar(13) 
	id bigint [default:'nextval('polaris.testkittype_id_seq'::regclass)']
	fluidtype varchar(10) [default:''OIL'::character varying']
}

Table persistentreportcontextfilter {
	persistentreportcontext bigint 
	position integer 
	required boolean 
	inclusion varchar(3) 
	field varchar(35) 
	comparison varchar(16) 
	value varchar(32) 
}

Table phone {
	countryprefix integer 
	extension varchar(8) 
	number varchar(35) 
	id bigint [default:'nextval('polaris.phone_id'::regclass)']
	version integer [default:'1']
}

Table componentmodel {
	id bigint 
	version integer 
	model varchar(3) 
	name varchar(30) 
	manufacturerid bigint 
}

Table ferrography {
	id bigint 
	sample bigint 
	dataanalyst bigint 
	datecreated timestamp without time zone 
	datemodified timestamp without time zone 
	severity integer 
	comments varchar(4096) 
	zzabr_minimum numeric 
	zzabr_maximum numeric 
	zzabr_severity integer 
	zzalu_minimum numeric 
	zzalu_maximum numeric 
	zzalu_severity integer 
	zzbab_minimum numeric 
	zzbab_maximum numeric 
	zzbab_severity integer 
	zzbox_minimum numeric 
	zzbox_maximum numeric 
	zzbox_severity integer 
	zzcor_minimum numeric 
	zzcor_maximum numeric 
	zzcor_severity integer 
	zzcua_minimum numeric 
	zzcua_maximum numeric 
	zzcua_severity integer 
	zzcut_minimum numeric 
	zzcut_maximum numeric 
	zzcut_severity integer 
	zzfat_minimum numeric 
	zzfat_maximum numeric 
	zzfat_severity integer 
	zzfer_minimum numeric 
	zzfer_maximum numeric 
	zzfer_severity integer 
	zzfic_minimum numeric 
	zzfic_maximum numeric 
	zzfic_severity integer 
	zzfrp_minimum numeric 
	zzfrp_maximum numeric 
	zzfrp_severity integer 
	zzlam_minimum numeric 
	zzlam_maximum numeric 
	zzlam_severity integer 
	zzpba_minimum numeric 
	zzpba_maximum numeric 
	zzpba_severity integer 
	zzrox_minimum numeric 
	zzrox_maximum numeric 
	zzrox_severity integer 
	zzrub_minimum numeric 
	zzrub_maximum numeric 
	zzrub_severity integer 
	zzsal_minimum numeric 
	zzsal_maximum numeric 
	zzsal_severity integer 
	zzsli_minimum numeric 
	zzsli_maximum numeric 
	zzsli_severity integer 
	zzsph_minimum numeric 
	zzsph_maximum numeric 
	zzsph_severity integer 
	zzud1_minimum numeric 
	zzud1_maximum numeric 
	zzud1_severity integer 
	zzud1_name varchar(64) 
	zzud2_minimum numeric 
	zzud2_maximum numeric 
	zzud2_severity integer 
	zzud2_name varchar(64) 
	zzud3_minimum numeric 
	zzud3_maximum numeric 
	zzud3_severity integer 
	zzud3_name varchar(64) 
	version integer 
}

Table subscriptioncarboncopy {
	subscription bigint 
	email varchar(255) 
}

Table printedlabeldata {
	id bigint 
	accountnumber varchar(14) 
	accountname varchar(128) 
	componentid varchar(30) 
	secondaryid varchar(30) 
	componenttype varchar(30) 
	fluidmanufacturer varchar(30) 
	fluidproduct varchar(30) 
	fluidgrade varchar(30) 
	datesampled date 
	dateprinted timestamp without time zone 
	fluidchanged varchar(15) 
	filterchanged varchar(15) 
}

Table testkit {
	unittype varchar(13) 
	id bigint 
	itemnumber varchar(12) 
	name varchar(35) 
	lastmodified timestamp without time zone 
	active boolean [default:'true']
	accountmask bigint 
	version integer 
}

Table personbyaccountmask {
	person bigint 
	accountmask bigint 
}

Table application {
	id bigint 
	version integer 
	limskey varchar(5) 
	name varchar(35) 
}

Table device {
	appname varchar(16) 
	appversion varchar(16) 
	ostype varchar(16) 
	osversion varchar(64) 
	devicedetail varchar(128) 
	devicetoken varchar(255) 
	lastused timestamp without time zone 
	id bigint 
	person bigint 
	authtoken varchar(255) 
	deviceid varchar(255) 
	devicename varchar(255) 
	notificationsubscriptionseverity integer 
	notificationfluidtypes integer 
}

Table samplesubmission {
	type varchar(30) 
	id bigint 
	sampledate date 
	componenttime bigint 
	fluidtime bigint 
	amountfluidadded bigint 
	fluidchanged varchar(15) 
	filterchanged varchar(15) 
	datelogged timestamp without time zone 
	component bigint 
	submittedby bigint 
	purchaseorder varchar(30) 
	comments varchar(100) 
	notestoanalyst varchar(120) 
	rush boolean [default:'false']
	submittedbarcode varchar(11) 
	itemnumber varchar(12) 
	componenttimeunit varchar(2) 
	fluidtimeunit varchar(2) 
	fluidaddedunit varchar(2) 
	fluidmanufacturerkey varchar(5) 
	fluidkey varchar(3) 
	fluidstandardkey varchar(3) 
	filtertypekey varchar(2) 
	filtermicronrating integer 
	version integer 
	additionaltesting varchar(120) 
}

Table dataanalyst {
	id bigint 
	version integer 
	active boolean 
	initials varchar(5) 
	person bigint 
}

Table iso_unit_reference {
	limskey varchar(5) 
	highlow varchar(1) 
	iso1 varchar(2) 
	iso2 varchar(2) 
	iso3 varchar(2) 
}

Table flag {
	limskey varchar(2) 
	severity integer 
}

Table matview_samples {
	sampleid bigint 
	componentid bigint 
	accountnumber varchar(16) 
	accountname varchar(128) 
	componentname varchar(30) 
	componenttypename varchar(30) 
	labidlabnumber text 
	severity integer 
	fluidtype character(1) 
	sampledate timestamp without time zone 
	feedbackstatus varchar(2) 
	postedmessages bigint 
	datecompleted timestamp without time zone 
	datereceived timestamp without time zone 
	secondaryid varchar(30) 
	trackingnumber varchar(11) 
	dateapproved timestamp without time zone 
}

Table testcode {
	limskey varchar(5) 
	unitofmeasuremnemonic varchar(42) 
	printorder integer 
	enumname varchar(6) [default:'''::character varying']
}

Table horizonnews {
	lineorder integer 
	id bigint [default:'nextval('polaris.horizonnews_id_seq'::regclass)']
	notification text 
	expiration timestamp without time zone 
}

Table lookup_working_days {
	labid varchar(1) 
	day timestamp without time zone 
}

Table accountmaskpermission {
	accountmask bigint 
	spmdata boolean [default:'false']
}

Table restservicepermission {
	samplesubmissionpermission boolean [default:'false']
	id bigint 
	person bigint 
	authtoken varchar(255) 
	sampleresultspermission boolean [default:'false']
}

Table viewedsamples {
	person bigint 
	sample bigint 
}

Table viewedsamplesmobile {
	id bigint [default:'nextval('polaris.viewedsamplesmobile_id_seq'::regclass)']
	person bigint 
	sample bigint 
	timeviewed timestamp without time zone 
}

Table samplereportapprovalauthority {
	id bigint 
	person bigint 
	severity integer 
	accountmask bigint 
}

Table testmethod {
	limskey varchar(2) 
	namemnemonic varchar(16) 
}

Table bootstrap {
	type varchar(20) 
	completed timestamp without time zone 
	description varchar(255) 
	id integer [default:'nextval('polaris.bootstrap_id_seq'::regclass)']
}

Table translation {
	id bigint 
	variant varchar(128) 
	mnemonic varchar(512) 
	style varchar(128) 
	text varchar(4096) [default:'''::character varying']
	country varchar(2) [default:'''::character varying']
	language varchar(2) [default:'''::character varying']
}

Table commentcategory {
	id bigint 
	name varchar(35) 
	version integer 
}

Table persistentreportcontextsort {
	persistentreportcontext bigint 
	position integer 
	field varchar(35) 
	direction varchar(10) 
	defaultsort boolean 
}

Table alert {
	id bigint [default:'nextval('polaris.alert_id_seq'::regclass)']
	availabledate timestamp without time zone 
	expirationdate timestamp without time zone 
	mnemonic varchar(512) 
	detailurl varchar(512) 
	starttime timestamp without time zone 
	endtime timestamp without time zone 
	duration integer [default:'0']
}

Table persistentreportcontextrecipient {
	persistentreportcontext bigint 
	position integer 
	recipient varchar(127) 
}

Table lock {
	id varchar(48) 
	version integer 
}

Table photomicrograph {
	id bigint 
	sample bigint 
	dataanalyst bigint 
	datecreated timestamp without time zone 
	datemodified timestamp without time zone 
	magnification varchar(5) 
	title varchar(100) 
	volume varchar(5) 
	scale varchar(32) 
	image bytea 
	version integer 
}

Table component {
	id bigint 
	version integer 
	active boolean 
	alternatename varchar(30) 
	maximumpressure integer 
	name varchar(30) 
	sampleinterval integer 
	sampleintervalunit varchar(2) 
	samplepoint varchar(30) 
	sumpcapacity integer 
	sumpcapacityunit varchar(2) 
	application bigint 
	asset bigint 
	componentmodel bigint 
	filter bigint 
	fluidproduct bigint 
	manufacturerid bigint 
	componenttype bigint 
	defaultunit varchar(2) 
	fluidstandard bigint 
	wildcard1 varchar(30) 
	wildcard2 varchar(30) 
	wildcard3 varchar(30) 
}

Table sample {
	quadzseverity integer 
	_so_result varchar(12) 
	_so_resultvalue numeric 
	_so_flag varchar(2) 
	_qq_result varchar(12) 
	_qq_resultvalue numeric 
	_qq_flag varchar(2) 
	id bigint 
	labid varchar(1) 
	labnumber varchar(6) 
	status integer 
	jarcomment varchar(100) 
	complete boolean [default:'false']
	fluidtype character(1) 
	fluidadded numeric 
	fluidaddedunit varchar(2) 
	fluidchange varchar(1) 
	filterchange varchar(1) 
	dateapproved timestamp without time zone 
	datecompleted timestamp without time zone 
	dateentered timestamp without time zone 
	dateprocessed timestamp without time zone 
	datereceived timestamp without time zone 
	datesampled timestamp without time zone 
	datesampledincomplete varchar(8) 
	partnerid varchar(16) 
	componenttime numeric 
	componenttimeunit varchar(2) 
	fluidtime numeric 
	fluidtimeunit varchar(2) 
	barcode bigint 
	laboratory bigint 
	component bigint 
	filter bigint 
	fluidproduct bigint 
	fluidstandard bigint 
	approvalcomments varchar(1536) 
	dataanalyst bigint 
	severity integer 
	dateactionclosed timestamp without time zone 
	watermethod varchar(2) 
	sootmethod varchar(2) 
	fuelmethod varchar(2) 
	nitritemethod varchar(2) 
	particlemethod varchar(2) 
	_01_result varchar(12) 
	_01_resultvalue numeric 
	_01_flag varchar(2) 
	_02_result varchar(12) 
	_02_resultvalue numeric 
	_02_flag varchar(2) 
	_03_result varchar(12) 
	_03_resultvalue numeric 
	_03_flag varchar(2) 
	_04_result varchar(12) 
	_04_resultvalue numeric 
	_04_flag varchar(2) 
	_05_result varchar(12) 
	_05_resultvalue numeric 
	_05_flag varchar(2) 
	_06_result varchar(12) 
	_06_resultvalue numeric 
	_06_flag varchar(2) 
	_07_result varchar(12) 
	_07_resultvalue numeric 
	_07_flag varchar(2) 
	_08_result varchar(12) 
	_08_resultvalue numeric 
	_08_flag varchar(2) 
	_09_result varchar(12) 
	_09_resultvalue numeric 
	_09_flag varchar(2) 
	_10_result varchar(12) 
	_10_resultvalue numeric 
	_10_flag varchar(2) 
	_11_result varchar(12) 
	_11_resultvalue numeric 
	_11_flag varchar(2) 
	_12_result varchar(12) 
	_12_resultvalue numeric 
	_12_flag varchar(2) 
	_13_result varchar(12) 
	_13_resultvalue numeric 
	_13_flag varchar(2) 
	_14_result varchar(12) 
	_14_resultvalue numeric 
	_14_flag varchar(2) 
	_15_result varchar(12) 
	_15_resultvalue numeric 
	_15_flag varchar(2) 
	_16_result varchar(12) 
	_16_resultvalue numeric 
	_16_flag varchar(2) 
	_17_result varchar(12) 
	_17_resultvalue numeric 
	_17_flag varchar(2) 
	_18_result varchar(12) 
	_18_resultvalue numeric 
	_18_flag varchar(2) 
	_19_result varchar(12) 
	_19_resultvalue numeric 
	_19_flag varchar(2) 
	_20_result varchar(12) 
	_20_resultvalue numeric 
	_20_flag varchar(2) 
	_21_result varchar(12) 
	_21_resultvalue numeric 
	_21_flag varchar(2) 
	_22_result varchar(12) 
	_22_resultvalue numeric 
	_22_flag varchar(2) 
	_23_result varchar(12) 
	_23_resultvalue numeric 
	_23_flag varchar(2) 
	_24_result varchar(12) 
	_24_resultvalue numeric 
	_24_flag varchar(2) 
	_54_result varchar(12) 
	_54_resultvalue numeric 
	_54_flag varchar(2) 
	_5a_result varchar(12) 
	_5a_resultvalue numeric 
	_5a_flag varchar(2) 
	_5b_result varchar(12) 
	_5b_resultvalue numeric 
	_5b_flag varchar(2) 
	_5c_result varchar(12) 
	_5c_resultvalue numeric 
	_5c_flag varchar(2) 
	_5d_result varchar(12) 
	_5d_resultvalue numeric 
	_5d_flag varchar(2) 
	_82_result varchar(12) 
	_82_resultvalue numeric 
	_82_flag varchar(2) 
	_8a_result varchar(12) 
	_8a_resultvalue numeric 
	_8a_flag varchar(2) 
	_8b_result varchar(12) 
	_8b_resultvalue numeric 
	_8b_flag varchar(2) 
	_8c_result varchar(12) 
	_8c_resultvalue numeric 
	_8c_flag varchar(2) 
	_8d_result varchar(12) 
	_8d_resultvalue numeric 
	_8d_flag varchar(2) 
	_fe_result varchar(12) 
	_fe_resultvalue numeric 
	_fe_flag varchar(2) 
	_cr_result varchar(12) 
	_cr_resultvalue numeric 
	_cr_flag varchar(2) 
	_ni_result varchar(12) 
	_ni_resultvalue numeric 
	_ni_flag varchar(2) 
	_al_result varchar(12) 
	_al_resultvalue numeric 
	_al_flag varchar(2) 
	_cu_result varchar(12) 
	_cu_resultvalue numeric 
	_cu_flag varchar(2) 
	_pb_result varchar(12) 
	_pb_resultvalue numeric 
	_pb_flag varchar(2) 
	_sn_result varchar(12) 
	_sn_resultvalue numeric 
	_sn_flag varchar(2) 
	_si_result varchar(12) 
	_si_resultvalue numeric 
	_si_flag varchar(2) 
	_su_result varchar(12) 
	_su_resultvalue numeric 
	_su_flag varchar(2) 
	_ch_result varchar(12) 
	_ch_resultvalue numeric 
	_ch_flag varchar(2) 
	_n3_result varchar(12) 
	_n3_resultvalue numeric 
	_n3_flag varchar(2) 
	_gy_result varchar(12) 
	_gy_resultvalue numeric 
	_gy_flag varchar(2) 
	_fo_result varchar(12) 
	_fo_resultvalue numeric 
	_fo_flag varchar(2) 
	_at_result varchar(12) 
	_at_resultvalue numeric 
	_at_flag varchar(2) 
	_ol_result varchar(12) 
	_ol_resultvalue numeric 
	_ol_flag varchar(2) 
	_h1_result varchar(12) 
	_h1_resultvalue numeric 
	_h1_flag varchar(2) 
	_h2_result varchar(12) 
	_h2_resultvalue numeric 
	_h2_flag varchar(2) 
	_h3_result varchar(12) 
	_h3_resultvalue numeric 
	_h3_flag varchar(2) 
	_h4_result varchar(12) 
	_h4_resultvalue numeric 
	_h4_flag varchar(2) 
	_h5_result varchar(12) 
	_h5_resultvalue numeric 
	_h5_flag varchar(2) 
	_h6_result varchar(12) 
	_h6_resultvalue numeric 
	_h6_flag varchar(2) 
	_h7_result varchar(12) 
	_h7_resultvalue numeric 
	_h7_flag varchar(2) 
	_h8_result varchar(12) 
	_h8_resultvalue numeric 
	_h8_flag varchar(2) 
	_b1_result varchar(12) 
	_b1_resultvalue numeric 
	_b1_flag varchar(2) 
	_b2_result varchar(12) 
	_b2_resultvalue numeric 
	_b2_flag varchar(2) 
	_b3_result varchar(12) 
	_b3_resultvalue numeric 
	_b3_flag varchar(2) 
	_r1_result varchar(12) 
	_r1_resultvalue numeric 
	_r1_flag varchar(2) 
	_r2_result varchar(12) 
	_r2_resultvalue numeric 
	_r2_flag varchar(2) 
	_r3_result varchar(12) 
	_r3_resultvalue numeric 
	_r3_flag varchar(2) 
	_r4_result varchar(12) 
	_r4_resultvalue numeric 
	_r4_flag varchar(2) 
	_r5_result varchar(12) 
	_r5_resultvalue numeric 
	_r5_flag varchar(2) 
	_r6_result varchar(12) 
	_r6_resultvalue numeric 
	_r6_flag varchar(2) 
	_r7_result varchar(12) 
	_r7_resultvalue numeric 
	_r7_flag varchar(2) 
	_r8_result varchar(12) 
	_r8_resultvalue numeric 
	_r8_flag varchar(2) 
	_cp_result varchar(12) 
	_cp_resultvalue numeric 
	_cp_flag varchar(2) 
	_pp_result varchar(12) 
	_pp_resultvalue numeric 
	_pp_flag varchar(2) 
	_cuu_result varchar(12) 
	_cuu_resultvalue numeric 
	_cuu_flag varchar(2) 
	_cw_result varchar(12) 
	_cw_resultvalue numeric 
	_cw_flag varchar(2) 
	_f1_result varchar(12) 
	_f1_resultvalue numeric 
	_f1_flag varchar(2) 
	_f2_result varchar(12) 
	_f2_resultvalue numeric 
	_f2_flag varchar(2) 
	_f3_result varchar(12) 
	_f3_resultvalue numeric 
	_f3_flag varchar(2) 
	_f4_result varchar(12) 
	_f4_resultvalue numeric 
	_f4_flag varchar(2) 
	_f5_result varchar(12) 
	_f5_resultvalue numeric 
	_f5_flag varchar(2) 
	_f6_result varchar(12) 
	_f6_resultvalue numeric 
	_f6_flag varchar(2) 
	_fl_result varchar(12) 
	_fl_resultvalue numeric 
	_fl_flag varchar(2) 
	_fs_result varchar(12) 
	_fs_resultvalue numeric 
	_fs_flag varchar(2) 
	_fp_result varchar(12) 
	_fp_resultvalue numeric 
	_fp_flag varchar(2) 
	_fy_result varchar(12) 
	_fy_resultvalue numeric 
	_fy_flag varchar(2) 
	_pi_result varchar(12) 
	_pi_resultvalue numeric 
	_pi_flag varchar(2) 
	_pu_result varchar(12) 
	_pu_resultvalue numeric 
	_pu_flag varchar(2) 
	_s0_result varchar(12) 
	_s0_resultvalue numeric 
	_s0_flag varchar(2) 
	_s1_result varchar(12) 
	_s1_resultvalue numeric 
	_s1_flag varchar(2) 
	_s2_result varchar(12) 
	_s2_resultvalue numeric 
	_s2_flag varchar(2) 
	_s3_result varchar(12) 
	_s3_resultvalue numeric 
	_s3_flag varchar(2) 
	_s4_result varchar(12) 
	_s4_resultvalue numeric 
	_s4_flag varchar(2) 
	_s5_result varchar(12) 
	_s5_resultvalue numeric 
	_s5_flag varchar(2) 
	_t1_result varchar(12) 
	_t1_resultvalue numeric 
	_t1_flag varchar(2) 
	_t2_result varchar(12) 
	_t2_resultvalue numeric 
	_t2_flag varchar(2) 
	_ti_result varchar(12) 
	_ti_resultvalue numeric 
	_ti_flag varchar(2) 
	_tu_result varchar(12) 
	_tu_resultvalue numeric 
	_tu_flag varchar(2) 
	_u1_result varchar(12) 
	_u1_resultvalue numeric 
	_u1_flag varchar(2) 
	_u2_result varchar(12) 
	_u2_resultvalue numeric 
	_u2_flag varchar(2) 
	_w1_result varchar(12) 
	_w1_resultvalue numeric 
	_w1_flag varchar(2) 
	_w2_result varchar(12) 
	_w2_resultvalue numeric 
	_w2_flag varchar(2) 
	_w3_result varchar(12) 
	_w3_resultvalue numeric 
	_w3_flag varchar(2) 
	_w4_result varchar(12) 
	_w4_resultvalue numeric 
	_w4_flag varchar(2) 
	_w5_result varchar(12) 
	_w5_resultvalue numeric 
	_w5_flag varchar(2) 
	_x1_result varchar(12) 
	_x1_resultvalue numeric 
	_x1_flag varchar(2) 
	_x2_result varchar(12) 
	_x2_resultvalue numeric 
	_x2_flag varchar(2) 
	_x3_result varchar(12) 
	_x3_resultvalue numeric 
	_x3_flag varchar(2) 
	_aa_result varchar(12) 
	_aa_resultvalue numeric 
	_aa_flag varchar(2) 
	_ab_result varchar(12) 
	_ab_resultvalue numeric 
	_ab_flag varchar(2) 
	_ac_result varchar(12) 
	_ac_resultvalue numeric 
	_ac_flag varchar(2) 
	_ad_result varchar(12) 
	_ad_resultvalue numeric 
	_ad_flag varchar(2) 
	_af_result varchar(12) 
	_af_resultvalue numeric 
	_af_flag varchar(2) 
	_ai_result varchar(12) 
	_ai_resultvalue numeric 
	_ai_flag varchar(2) 
	_alu_result varchar(12) 
	_alu_resultvalue numeric 
	_alu_flag varchar(2) 
	_an_result varchar(12) 
	_an_resultvalue numeric 
	_an_flag varchar(2) 
	_ap_result varchar(12) 
	_ap_resultvalue numeric 
	_ap_flag varchar(2) 
	_ar_result varchar(12) 
	_ar_resultvalue numeric 
	_ar_flag varchar(2) 
	_as_result varchar(12) 
	_as_resultvalue numeric 
	_as_flag varchar(2) 
	_bg_result varchar(12) 
	_bg_resultvalue numeric 
	_bg_flag varchar(2) 
	_bl_result varchar(12) 
	_bl_resultvalue numeric 
	_bl_flag varchar(2) 
	_bn_result varchar(12) 
	_bn_resultvalue numeric 
	_bn_flag varchar(2) 
	_bp_result varchar(12) 
	_bp_resultvalue numeric 
	_bp_flag varchar(2) 
	_bt_result varchar(12) 
	_bt_resultvalue numeric 
	_bt_flag varchar(2) 
	_bx_result varchar(12) 
	_bx_resultvalue numeric 
	_bx_flag varchar(2) 
	_c1_result varchar(12) 
	_c1_resultvalue numeric 
	_c1_flag varchar(2) 
	_c2_result varchar(12) 
	_c2_resultvalue numeric 
	_c2_flag varchar(2) 
	_ca_result varchar(12) 
	_ca_resultvalue numeric 
	_ca_flag varchar(2) 
	_cc_result varchar(12) 
	_cc_resultvalue numeric 
	_cc_flag varchar(2) 
	_cf_result varchar(12) 
	_cf_resultvalue numeric 
	_cf_flag varchar(2) 
	_ci_result varchar(12) 
	_ci_resultvalue numeric 
	_ci_flag varchar(2) 
	_cl_result varchar(12) 
	_cl_resultvalue numeric 
	_cl_flag varchar(2) 
	_cn_result varchar(12) 
	_cn_resultvalue numeric 
	_cn_flag varchar(2) 
	_co_result varchar(12) 
	_co_resultvalue numeric 
	_co_flag varchar(2) 
	_cru_result varchar(12) 
	_cru_resultvalue numeric 
	_cru_flag varchar(2) 
	_ct_result varchar(12) 
	_ct_resultvalue numeric 
	_ct_flag varchar(2) 
	_cx_result varchar(12) 
	_cx_resultvalue numeric 
	_cx_flag varchar(2) 
	_d0_result varchar(12) 
	_d0_resultvalue numeric 
	_d0_flag varchar(2) 
	_d1_result varchar(12) 
	_d1_resultvalue numeric 
	_d1_flag varchar(2) 
	_d2_result varchar(12) 
	_d2_resultvalue numeric 
	_d2_flag varchar(2) 
	_d3_result varchar(12) 
	_d3_resultvalue numeric 
	_d3_flag varchar(2) 
	_d4_result varchar(12) 
	_d4_resultvalue numeric 
	_d4_flag varchar(2) 
	_ds_result varchar(12) 
	_ds_resultvalue numeric 
	_ds_flag varchar(2) 
	_dy_result varchar(12) 
	_dy_resultvalue numeric 
	_dy_flag varchar(2) 
	_fplus_result varchar(12) 
	_fplus_resultvalue numeric 
	_fplus_flag varchar(2) 
	_fa_result varchar(12) 
	_fa_resultvalue numeric 
	_fa_flag varchar(2) 
	_fb_result varchar(12) 
	_fb_resultvalue numeric 
	_fb_flag varchar(2) 
	_fc_result varchar(12) 
	_fc_resultvalue numeric 
	_fc_flag varchar(2) 
	_fd_result varchar(12) 
	_fd_resultvalue numeric 
	_fd_flag varchar(2) 
	_fi_result varchar(12) 
	_fi_resultvalue numeric 
	_fi_flag varchar(2) 
	_fm_result varchar(12) 
	_fm_resultvalue numeric 
	_fm_flag varchar(2) 
	_ft_result varchar(12) 
	_ft_resultvalue numeric 
	_ft_flag varchar(2) 
	_fx_result varchar(12) 
	_fx_resultvalue numeric 
	_fx_flag varchar(2) 
	_fz_result varchar(12) 
	_fz_resultvalue numeric 
	_fz_flag varchar(2) 
	_gl_result varchar(12) 
	_gl_resultvalue numeric 
	_gl_flag varchar(2) 
	_gm_result varchar(12) 
	_gm_resultvalue numeric 
	_gm_flag varchar(2) 
	_gv_result varchar(12) 
	_gv_resultvalue numeric 
	_gv_flag varchar(2) 
	_hd_result varchar(12) 
	_hd_resultvalue numeric 
	_hd_flag varchar(2) 
	_hp_result varchar(12) 
	_hp_resultvalue numeric 
	_hp_flag varchar(2) 
	_i1_result varchar(12) 
	_i1_resultvalue numeric 
	_i1_flag varchar(2) 
	_i2_result varchar(12) 
	_i2_resultvalue numeric 
	_i2_flag varchar(2) 
	_i3_result varchar(12) 
	_i3_resultvalue numeric 
	_i3_flag varchar(2) 
	_k1_result varchar(12) 
	_k1_resultvalue numeric 
	_k1_flag varchar(2) 
	_lc_result varchar(12) 
	_lc_resultvalue numeric 
	_lc_flag varchar(2) 
	_lx_result varchar(12) 
	_lx_resultvalue numeric 
	_lx_flag varchar(2) 
	_mp_result varchar(12) 
	_mp_resultvalue numeric 
	_mp_flag varchar(2) 
	_n2_result varchar(12) 
	_n2_resultvalue numeric 
	_n2_flag varchar(2) 
	_nt_result varchar(12) 
	_nt_resultvalue numeric 
	_nt_flag varchar(2) 
	_os_result varchar(12) 
	_os_resultvalue numeric 
	_os_flag varchar(2) 
	_ox_result varchar(12) 
	_ox_resultvalue numeric 
	_ox_flag varchar(2) 
	_p1_result varchar(12) 
	_p1_resultvalue numeric 
	_p1_flag varchar(2) 
	_p2_result varchar(12) 
	_p2_resultvalue numeric 
	_p2_flag varchar(2) 
	_p3_result varchar(12) 
	_p3_resultvalue numeric 
	_p3_flag varchar(2) 
	_p4_result varchar(12) 
	_p4_resultvalue numeric 
	_p4_flag varchar(2) 
	_p5_result varchar(12) 
	_p5_resultvalue numeric 
	_p5_flag varchar(2) 
	_p6_result varchar(12) 
	_p6_resultvalue numeric 
	_p6_flag varchar(2) 
	_p7_result varchar(12) 
	_p7_resultvalue numeric 
	_p7_flag varchar(2) 
	_p8_result varchar(12) 
	_p8_resultvalue numeric 
	_p8_flag varchar(2) 
	_ph_result varchar(12) 
	_ph_resultvalue numeric 
	_ph_flag varchar(2) 
	_pm_result varchar(12) 
	_pm_resultvalue numeric 
	_pm_flag varchar(2) 
	_pq_result varchar(12) 
	_pq_resultvalue numeric 
	_pq_flag varchar(2) 
	_pt_result varchar(12) 
	_pt_resultvalue numeric 
	_pt_flag varchar(2) 
	_pw_result varchar(12) 
	_pw_resultvalue numeric 
	_pw_flag varchar(2) 
	_ra_result varchar(12) 
	_ra_resultvalue numeric 
	_ra_flag varchar(2) 
	_rb_result varchar(12) 
	_rb_resultvalue numeric 
	_rb_flag varchar(2) 
	_re_result varchar(12) 
	_re_resultvalue numeric 
	_re_flag varchar(2) 
	_ru_result varchar(12) 
	_ru_resultvalue numeric 
	_ru_flag varchar(2) 
	_sa_result varchar(12) 
	_sa_resultvalue numeric 
	_sa_flag varchar(2) 
	_sc_result varchar(12) 
	_sc_resultvalue numeric 
	_sc_flag varchar(2) 
	_se_result varchar(12) 
	_se_resultvalue numeric 
	_se_flag varchar(2) 
	_sf_result varchar(12) 
	_sf_resultvalue numeric 
	_sf_flag varchar(2) 
	_sg_result varchar(12) 
	_sg_resultvalue numeric 
	_sg_flag varchar(2) 
	_sh_result varchar(12) 
	_sh_resultvalue numeric 
	_sh_flag varchar(2) 
	_sm_result varchar(12) 
	_sm_resultvalue numeric 
	_sm_flag varchar(2) 
	_snu_result varchar(12) 
	_snu_resultvalue numeric 
	_snu_flag varchar(2) 
	_sp_result varchar(12) 
	_sp_resultvalue numeric 
	_sp_flag varchar(2) 
	_st_result varchar(12) 
	_st_resultvalue numeric 
	_st_flag varchar(2) 
	_td_result varchar(12) 
	_td_resultvalue numeric 
	_td_flag varchar(2) 
	_th_result varchar(12) 
	_th_resultvalue numeric 
	_th_flag varchar(2) 
	_to_result varchar(12) 
	_to_resultvalue numeric 
	_to_flag varchar(2) 
	_tt_result varchar(12) 
	_tt_resultvalue numeric 
	_tt_flag varchar(2) 
	_vr_result varchar(12) 
	_vr_resultvalue numeric 
	_vr_flag varchar(2) 
	_v0_result varchar(12) 
	_v0_resultvalue numeric 
	_v0_flag varchar(2) 
	_v1_result varchar(12) 
	_v1_resultvalue numeric 
	_v1_flag varchar(2) 
	_v2_result varchar(12) 
	_v2_resultvalue numeric 
	_v2_flag varchar(2) 
	_v3_result varchar(12) 
	_v3_resultvalue numeric 
	_v3_flag varchar(2) 
	_v4_result varchar(12) 
	_v4_resultvalue numeric 
	_v4_flag varchar(2) 
	_v5_result varchar(12) 
	_v5_resultvalue numeric 
	_v5_flag varchar(2) 
	_v6_result varchar(12) 
	_v6_resultvalue numeric 
	_v6_flag varchar(2) 
	_v7_result varchar(12) 
	_v7_resultvalue numeric 
	_v7_flag varchar(2) 
	_vc_result varchar(12) 
	_vc_resultvalue numeric 
	_vc_flag varchar(2) 
	_vf_result varchar(12) 
	_vf_resultvalue numeric 
	_vf_flag varchar(2) 
	_vi_result varchar(12) 
	_vi_resultvalue numeric 
	_vi_flag varchar(2) 
	_vm_result varchar(12) 
	_vm_resultvalue numeric 
	_vm_flag varchar(2) 
	_vn_result varchar(12) 
	_vn_resultvalue numeric 
	_vn_flag varchar(2) 
	_vo_result varchar(12) 
	_vo_resultvalue numeric 
	_vo_flag varchar(2) 
	_vs_result varchar(12) 
	_vs_resultvalue numeric 
	_vs_flag varchar(2) 
	_vv_result varchar(12) 
	_vv_resultvalue numeric 
	_vv_flag varchar(2) 
	_wa_result varchar(12) 
	_wa_resultvalue numeric 
	_wa_flag varchar(2) 
	_wc_result varchar(12) 
	_wc_resultvalue numeric 
	_wc_flag varchar(2) 
	_wk_result varchar(12) 
	_wk_resultvalue numeric 
	_wk_flag varchar(2) 
	_wp_result varchar(12) 
	_wp_resultvalue numeric 
	_wp_flag varchar(2) 
	_ws_result varchar(12) 
	_ws_resultvalue numeric 
	_ws_flag varchar(2) 
	_wu_result varchar(12) 
	_wu_resultvalue numeric 
	_wu_flag varchar(2) 
	version integer 
	_d5_result varchar(12) 
	_d5_resultvalue numeric 
	_d5_flag varchar(2) 
	_d6_result varchar(12) 
	_d6_resultvalue numeric 
	_d6_flag varchar(2) 
	_d7_result varchar(12) 
	_d7_resultvalue numeric 
	_d7_flag varchar(2) 
	_k2_result varchar(12) 
	_k2_resultvalue numeric 
	_k2_flag varchar(2) 
	_h0_result varchar(12) 
	_h0_resultvalue numeric 
	_h0_flag varchar(2) 
	_h9_result varchar(12) 
	_h9_resultvalue numeric 
	_h9_flag varchar(2) 
	_x4_result varchar(12) 
	_x4_resultvalue numeric 
	_x4_flag varchar(2) 
	feedbackstatus varchar(2) [default:''NE'::character varying']
	_a1_result varchar(12) 
	_a1_resultvalue numeric 
	purchaseorder varchar(255) 
	testpackage varchar(255) 
	rush varchar(6) 
	rushrequestor varchar(255) 
	rushticket varchar(255) 
	cnotes varchar(120) 
	_a1_flag varchar(2) 
	_a2_result varchar(12) 
	_a2_resultvalue numeric 
	_a2_flag varchar(2) 
	_a4_result varchar(12) 
	_a4_resultvalue numeric 
	_a4_flag varchar(2) 
	_ia_result varchar(12) 
	_ia_resultvalue numeric 
	_ia_flag varchar(2) 
	_a5_result varchar(12) 
	_a5_resultvalue numeric 
	_a5_flag varchar(2) 
	_ma_result varchar(12) 
	_ma_resultvalue numeric 
	_ma_flag varchar(2) 
	_mi_result varchar(12) 
	_mi_resultvalue numeric 
	_mi_flag varchar(2) 
	_mt_result varchar(12) 
	_mt_resultvalue numeric 
	_mt_flag varchar(2) 
	_wr_result varchar(12) 
	_wr_resultvalue numeric 
	_wr_flag varchar(2) 
}

Table logo {
	id bigint 
	version integer 
	image bytea 
	name varchar(255) 
}

Table profileproperty {
	hierarchymember bigint 
	setting varchar(255) 
	key varchar(255) 
}

Table host {
	virtualhostname varchar(255) 
	emailhostname varchar(255) 
	program bigint 
	index integer [default:'0']
}

Table componenttype {
	id bigint 
	version integer 
	limskey varchar(5) 
	name varchar(30) 
	fluidtype varchar(10) [default:''OIL'::character varying']
}

Table program {
	id bigint 
	version integer 
	description varchar(255) 
	name varchar(128) 
	timezone varchar(255) 
	activeprogram bigint 
	accountnumberprefix varchar(14) 
	applicationname varchar(128) 
	logouturl varchar(255) 
	style varchar(255) 
	applicationlogo bigint 
	logo bigint 
	privatelabel bigint 
	reportlogo bigint 
	reportapplicationlogo bigint 
	advertisements bigint 
	country varchar(2) [default:'''::character varying']
	language varchar(2) [default:'''::character varying']
	report_frequency varchar(20) 
	report_format varchar(30) 
	reportdigest_frequency varchar(20) 
	reportdigest_format varchar(30) 
	hold_frequency varchar(20) 
	hold_format varchar(30) 
	holddigest_frequency varchar(20) 
	holddigest_format varchar(30) 
	receipt_frequency varchar(20) 
	receipt_format varchar(30) 
	receiptdigest_frequency varchar(20) 
	receiptdigest_format varchar(30) 
	nonhosted bigint 
	quadz_frequency varchar(20) 
	quadz_format varchar(30) 
}

Table commentcodereasons {
	commentcodeid bigint 
	id bigint 
}

Table asset {
	id bigint 
	version integer 
	account bigint 
}

Table authority {
	hierarchymember bigint 
	feature varchar(255) 
	permission integer 
}

Table barcodeaccountexemption {
	sourcemask varchar(6) 
	targetmask varchar(6) 
}

Table testresultlimit {
	id bigint 
	componenttype bigint 
	testcode varchar(5) 
	fluidtype varchar(1) 
	program bigint 
	minimumvalue numeric 
	minimum varchar(50) 
	maximumvalue numeric 
	maximum varchar(50) 
	infosource varchar(50) 
	version integer 
}

Table storeexport {
	id bigint 
	createddate timestamp without time zone 
	exporteddate timestamp without time zone 
	actiontaken varchar(1) 
	type varchar(64) 
	data text 
}

Table samplehold {
	internalreason varchar(255) 
	id bigint 
	sample bigint 
	accountnumber varchar(14) 
	componentid varchar(30) 
	level varchar(1) 
	datereceived date 
	dateresolved date 
	shipmethod varchar(16) 
	contactinfo1 varchar(30) 
	contactinfo2 varchar(30) 
	contactinfo3 varchar(30) 
	phonenumber varchar(30) 
	unittype varchar(30) 
	heldreason1 varchar(30) 
	heldreason2 varchar(30) 
	comments varchar(255) 
	usercomments text 
	submittedon timestamp without time zone 
	submittedby bigint 
	version integer 
}

Table filter {
	id bigint 
	version integer 
	micronrating integer 
	filtertypeid bigint 
}

Table fluidstandard {
	id bigint 
	version integer 
	limskey varchar(3) 
	name varchar(30) 
}

Table wicketpagestore {
	key varchar(255) 
	obj bytea 
	created timestamp without time zone 
}

Table samplecomment {
	sample bigint 
	position integer 
	commentcode bigint 
	customerworkorder varchar(12) 
	customerfinding varchar(20) 
	customercomment varchar(1024) 
	estimatedsavings numeric 
	lastmodification timestamp without time zone 
}

Table postedmessage {
	id bigint 
	version integer 
	date timestamp without time zone 
	text varchar(1500) 
	creator bigint 
	sample bigint 
}

Table mailreportbatchentry {
	mailreportbatchentity_id bigint 
	labid varchar(1) 
	labnumber varchar(6) 
	copies integer [default:'1']
}

Table manufacturer {
	id bigint 
	version integer 
	limskey varchar(5) 
	name varchar(30) 
	producttype varchar(255) 
}

Table ferrographyimageresult {
	ferrography bigint 
	position integer 
	title varchar(100) 
	comments varchar(4096) 
	magnification varchar(5) 
	type varchar(12) 
	image bytea 
}

Table subscription {
	id bigint 
	version integer 
	displaysymbols boolean 
	includegraphs boolean 
	includecomments boolean 
	includemessages boolean 
	includeprimaryemail boolean 
	name varchar(255) 
	hierarchymemberid bigint 
	startdate timestamp without time zone 
	enddate timestamp without time zone 
	custommessage varchar(1024) 
	language varchar(2) [default:'''::character varying']
	report_frequency varchar(20) 
	report_format varchar(30) 
	digest_frequency varchar(20) 
	digest_format varchar(30) 
	hold_frequency varchar(20) 
	hold_format varchar(30) 
	receipt_frequency varchar(20) 
	receipt_format varchar(30) 
	holddigest_frequency varchar(20) 
	holddigest_format varchar(30) 
	receiptdigest_frequency varchar(20) 
	receiptdigest_format varchar(30) 
	quadz_frequency varchar(20) [default:''NEVER'::character varying']
	quadz_format varchar(30) 
}

Table accountmask {
	id bigint 
	version integer 
	description varchar(255) 
	name varchar(128) 
	timezone varchar(255) 
	activeprogram bigint 
	mask varchar(14) 
	program bigint 
	country varchar(2) [default:'''::character varying']
	language varchar(2) [default:'''::character varying']
}

Table matview_components {
	componentid bigint 
	accountnumber varchar(16) 
	accountname varchar(128) 
	componentname varchar(30) 
	componentalternatename varchar(30) 
	componenttypename varchar(30) 
	reportsonfile bigint 
	mostrecentsampledate timestamp without time zone 
	manufacturername varchar 
	componentmodelname varchar 
	sampleinterval integer 
	sampleintervalunit varchar(2) 
	duedate timestamp without time zone 
}

Table sampledocument {
	id bigint 
	sample bigint 
	filename varchar(256) 
	mimetype varchar(256) 
	document bytea 
	version integer 
}

Table subscriptionreporttypes {
	subscriptionid bigint 
	reporttype varchar 
}

Table subscriptionfilter {
	subscription bigint 
	position integer 
	inclusion varchar(3) 
	field varchar(35) 
	comparison varchar(16) 
	value varchar(32) 
	required boolean 
}

Table laboratory {
	id bigint 
	version integer 
	description varchar(255) 
	name varchar(128) 
	timezone varchar(255) 
	activeprogram bigint 
	shortname varchar(64) 
	sourcecode varchar(3) 
	thirdparty boolean 
	country varchar(2) [default:'''::character varying']
	language varchar(2) [default:'''::character varying']
	emailaddress varchar(128) 
	address bigint 
	local bigint 
	fax bigint 
	tollfree bigint 
}

Table temp_samplesubmission_testkit_relations {
	samplesubmission bigint 
	itemnumber varchar(6) 
	accountmaskid bigint 
	name varchar(35) 
	accountmask varchar(14) 
}

Table barcode {
	id bigint 
	version integer 
	type character(1) 
	active boolean 
	barcode varchar(11) 
	countryrestriction varchar(2) 
	currencycode varchar(6) 
	datereceived timestamp without time zone 
	internal boolean 
	itemnumber varchar(12) 
	ordernumber varchar(6) 
	price numeric 
	testpackage varchar(6) 
	account bigint 
	rush boolean [default:'false']
	generated boolean [default:'false']
	shippedfrom varchar(5) 
}

Table account {
	id bigint 
	version integer 
	name varchar(128) 
	accountnumber varchar(16) 
	program bigint 
	mailreportwithlabel boolean [default:'false']
	partnerid varchar(48) 
	accountmask bigint 
	duplicatecomponentrestriction varchar(1) [default:''Y'::character varying']
	reportemailaddress varchar(128) 
	reportaddress bigint 
	reportphone bigint 
	primarybillingconfiguration bigint 
	rushinvoicelevel varchar(1) 
	salesregion varchar(2) 
	purchaseorderrequired boolean [default:'false']
	defaultapplication bigint 
	submissioncommentsrequired boolean [default:'false']
	suspended boolean [default:'false']
}

Table mailreportbatch {
	id bigint 
	batch varchar(10) 
	recipient varchar(50) 
	company varchar(50) 
	address1 varchar(50) 
	address2 varchar(50) 
	city varchar(50) 
	territory varchar(2) 
	region varchar(50) 
	postalcode varchar(9) 
	country varchar(2) 
	createddate timestamp without time zone 
	createdby varchar(128) 
	printed boolean [default:'false']
	printeddate timestamp without time zone 
	printedby varchar(128) 
	version integer 
}

Table subscriptionseverities {
	subscription bigint 
	severity integer 
}

Table privatelabel {
	id bigint 
	version integer 
	description varchar(255) 
	name varchar(128) 
	timezone varchar(255) 
	activeprogram bigint 
	code varchar(6) 
	country varchar(2) [default:'''::character varying']
	language varchar(2) [default:'''::character varying']
	report_frequency varchar(20) [default:''ASAP'::character varying']
	report_format varchar(30) [default:''APPLICATION_PDF'::character varying']
	reportdigest_frequency varchar(20) [default:''NEVER'::character varying']
	reportdigest_format varchar(30) 
	hold_frequency varchar(20) [default:''ASAP'::character varying']
	hold_format varchar(30) [default:''TEXT_HTML'::character varying']
	holddigest_frequency varchar(20) [default:''NEVER'::character varying']
	holddigest_format varchar(30) 
	receipt_frequency varchar(20) [default:''NEVER'::character varying']
	receipt_format varchar(30) 
	receiptdigest_frequency varchar(20) [default:''NEVER'::character varying']
	receiptdigest_format varchar(30) 
	quadz_frequency varchar(20) 
	quadz_format varchar(30) 
}

Table commentreason {
	id bigint 
	limskey varchar(5) 
	name varchar(35) 
	category bigint 
	version integer 
}

Table accounttier {
	id bigint 
	version integer 
	description varchar(255) 
	name varchar(128) 
	timezone varchar(255) 
	activeprogram bigint 
	maxlength integer 
	minlength integer 
	program bigint 
	country varchar(2) [default:'''::character varying']
	language varchar(2) [default:'''::character varying']
	report_frequency varchar(20) 
	report_format varchar(30) 
	reportdigest_frequency varchar(20) 
	reportdigest_format varchar(30) 
	hold_frequency varchar(20) 
	hold_format varchar(30) 
	holddigest_frequency varchar(20) 
	holddigest_format varchar(30) 
	receipt_frequency varchar(20) 
	receipt_format varchar(30) 
	receiptdigest_frequency varchar(20) 
	receiptdigest_format varchar(30) 
	quadz_frequency varchar(20) 
	quadz_format varchar(30) 
}

Table shockpulsemethod {
	id bigint 
	sample bigint 
	dataanalyst bigint 
	datecreated timestamp without time zone 
	datemodified timestamp without time zone 
	samplereason varchar(32) 
	warrantydetail varchar(28) 
	airendchange boolean [default:'false']
	stage varchar(16) 
	version integer 
}

Table cachedreport {
	id varchar(48) 
	version integer 
	accesskey varchar(48) 
	created timestamp without time zone 
	report bytea 
	export bytea 
	exportsize bigint [default:'(0)::bigint']
	reporttype varchar(50) 
}

Table person {
	logindate timestamp without time zone 
	logoutdate timestamp without time zone 
	postedmessage boolean [default:'true']
	userregistration bigint 
	id bigint 
	version integer 
	description varchar(255) 
	name varchar(128) 
	timezone varchar(255) 
	activeprogram bigint 
	password varchar(256) 
	username varchar(128) 
	comment varchar(100) 
	registrationdate date 
	expirationdate timestamp without time zone 
	activationdate date 
	lastlogindate date 
	registrationkey varchar 
	auditor bigint 
	status varchar(127) 
	registrationdenialreason varchar(255) 
	emailaddress varchar(128) 
	phone bigint 
	loginenabled boolean [default:'false']
	passwordreset boolean [default:'false']
	locked boolean [default:'false']
	country varchar(2) [default:'''::character varying']
	language varchar(2) [default:'''::character varying']
	restserviceuser boolean [default:'false']
	acceptedtermsdate timestamp without time zone 
	approvaldate date 
}

Table advertisement {
	image bytea 
	program bigint 
}

Table accountmaskrestriction {
	mask varchar(14) 
}

Table address {
	agent varchar(127) 
	city varchar(127) 
	pobox varchar(127) 
	postcode varchar(15) 
	region varchar(127) 
	street varchar(127) 
	country varchar(2) [default:'''::character varying']
	id bigint [default:'nextval('polaris.address_id'::regclass)']
	version integer [default:'1']
}

Table powerbi_informational_cause {
	mnemonic varchar(512) 
	cause varchar(4096) 
}

Table stagedata {
	id bigint 
	carpetdecibel integer 
	initialdecibel integer 
	maximumdecibel integer 
	type varchar(255) 
	analysis bigint 
	version integer 
}

Table programcontact {
	phone1 bigint 
	phone2 bigint 
	fax bigint 
	emailaddress varchar(128) 
	customerservicecenter varchar 
	program bigint 
	index integer 
}

Table samplenotification {
	labid varchar(1) 
	labnumber varchar(6) 
	severity integer 
	accountnumber varchar(14) 
	accountname varchar(128) 
	componentname varchar(30) 
	id bigint 
	sample bigint 
	type varchar(48) 
	sent timestamp without time zone 
	recipient varchar(128) 
	subscriber varchar(128) 
	subscriptionname varchar(255) 
}

Table persistentreportcontextproperty {
	persistentreportcontext bigint 
	property varchar(32) 
	setting text 
}

